name = input("Enter your Name : ")
clg = input("Enter your College : ")
cgpa = float(input("Enter your current CGPA : "))
pl = input("Enter your preferred programming language : ")
problems = int(input("Enter no.of leetcode problems done : "))
gname = input("Enter your github username : ")
goal = input("Enter your career goal : ")

print("====================================")
print(f"          {name}'s Profile")
print("====================================")
print(f"Name : {name}")
print(f"College : {clg}")
print(f"CGPA : {cgpa}")
print(f"Language : {pl}")
print(f"LeetCode : {problems}")
print(f"Github : {gname}")
print(f"Goal : {goal}")